---
title: "Example vignette"
author:
    - name: Daniela Corbetta
      affiliation: Department of Statistical Sciences, University of Padova 
      email: daniela.corbetta@phd.unipd.it
package: scConform
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
vignette: >
  %\VignetteIndexEntry{scConform}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

# Load useful packages

```{r libraries, message=FALSE}
library(scConform)
library(SingleCellExperiment)
library(VGAM)
library(foreach)
library(ontoProc)
library(MerfishData)
library(doParallel)
library(igraph)
library(scuttle)
library(scran)

`%notin%` <- Negate(`%in%`)

num_cores <- 2
cl1 <- makeCluster(num_cores)
registerDoParallel(cl1)
```

# Preliminaries

## Load data and cell ontology

As an example, we'll load the mouse ileum Merfish data from the MerfishData Bioconductor package. Load also the cell ontology trough the ontoProc Bioc package
```{r data}
spe.baysor <- MouseIleumPetukhov2021(segmentation = "baysor")
cl <- getOnto("cellOnto", "2023")
```
